### ISSUE TITLE
addClass and removeClass not working

### ISSUE THREAD

**Issue by sokki** [krawaller/kranium#9]
Hi,

first, thank you for this great Framework. I'm really loving it.

When i do a 
$(myview).addClass('class');
The myview.className change but the style don't apply. Same with removeClass().

**Comment by krawaller** [comment]
This is fixed in 0.1.4 and pushed to npm just this moment. I'd love your help to see if it works as expected!

Please note that the implementation is unaware of defaults or previous values, so if you for example would like to toggle a label between being black and red, your styles would have to explicitly say black and red. If you were to leave out black, Kranium wouldn't know anything about the default style being black, and the label would stay red.

Cheers

**Comment by sokki** [comment]
works well, thanks!

// edit
It's really too slow for my case. I just want to change the background color of a view on click. So i add a "selected" class. On the iPhone 3gs it took around 500ms to add the class ... compared to 5 ms for native bg changing :(
